/**
 * Seed: Cards catalog
 * Purpose: Populate all available cards in the game
 */

exports.seed = async function (knex) {
  // Delete existing entries
  await knex('cards').del();

  // Insert cards
  await knex('cards').insert([
    // ===== COMMON CARDS (HP) =====
    {
      id: 'card_hp_001',
      name: 'Novice Fighter',
      description: 'A beginner warrior with basic combat training',
      hp: 30,
      shield: 5,
      rarity: 'common',
      is_boss: false,
      image_url: null,
    },
    {
      id: 'card_hp_002',
      name: 'Village Guard',
      description: 'A stalwart defender of their hometown',
      hp: 35,
      shield: 8,
      rarity: 'common',
      is_boss: false,
      image_url: null,
    },
    {
      id: 'card_hp_003',
      name: 'Traveling Merchant',
      description: 'A merchant with surprising resilience',
      hp: 25,
      shield: 10,
      rarity: 'common',
      is_boss: false,
      image_url: null,
    },
    {
      id: 'card_hp_004',
      name: 'Forest Scout',
      description: 'A nimble scout from the woods',
      hp: 28,
      shield: 6,
      rarity: 'common',
      is_boss: false,
      image_url: null,
    },
    {
      id: 'card_hp_005',
      name: 'Town Militia',
      description: 'A citizen-soldier ready to defend',
      hp: 32,
      shield: 7,
      rarity: 'common',
      is_boss: false,
      image_url: null,
    },

    // ===== COMMON CARDS (SHIELD) =====
    {
      id: 'card_shield_001',
      name: 'Shield Bearer',
      description: 'Specializes in defensive tactics',
      hp: 20,
      shield: 15,
      rarity: 'common',
      is_boss: false,
      image_url: null,
    },
    {
      id: 'card_shield_002',
      name: 'Armor Smith',
      description: 'Crafts and wears heavy armor',
      hp: 22,
      shield: 18,
      rarity: 'common',
      is_boss: false,
      image_url: null,
    },
    {
      id: 'card_shield_003',
      name: 'Iron Wall',
      description: 'An immovable defensive position',
      hp: 25,
      shield: 20,
      rarity: 'common',
      is_boss: false,
      image_url: null,
    },

    // ===== COMMON CARDS (NORMAL ABILITY) =====
    {
      id: 'card_normal_001',
      name: 'Swordsman',
      description: 'A skilled blade wielder',
      hp: 30,
      shield: 8,
      rarity: 'common',
      is_boss: false,
      image_url: null,
    },
    {
      id: 'card_normal_002',
      name: 'Archer',
      description: 'Strikes from a distance',
      hp: 25,
      shield: 5,
      rarity: 'common',
      is_boss: false,
      image_url: null,
    },
    {
      id: 'card_normal_003',
      name: 'Spear Fighter',
      description: 'Wields a long-reaching spear',
      hp: 28,
      shield: 6,
      rarity: 'common',
      is_boss: false,
      image_url: null,
    },

    // ===== UNCOMMON CARDS (HP) =====
    {
      id: 'card_hp_006',
      name: 'Veteran Soldier',
      description: 'Battle-hardened and resilient',
      hp: 45,
      shield: 10,
      rarity: 'uncommon',
      is_boss: false,
      image_url: null,
    },
    {
      id: 'card_hp_007',
      name: 'Knight Errant',
      description: 'A wandering knight seeking glory',
      hp: 50,
      shield: 12,
      rarity: 'uncommon',
      is_boss: false,
      image_url: null,
    },
    {
      id: 'card_hp_008',
      name: 'Berserker',
      description: 'Trades defense for raw power',
      hp: 55,
      shield: 8,
      rarity: 'uncommon',
      is_boss: false,
      image_url: null,
    },

    // ===== UNCOMMON CARDS (SHIELD) =====
    {
      id: 'card_shield_004',
      name: 'Tower Guardian',
      description: 'Protects with unwavering dedication',
      hp: 30,
      shield: 25,
      rarity: 'uncommon',
      is_boss: false,
      image_url: null,
    },
    {
      id: 'card_shield_005',
      name: 'Bulwark',
      description: 'An impenetrable defense',
      hp: 28,
      shield: 30,
      rarity: 'uncommon',
      is_boss: false,
      image_url: null,
    },

    // ===== UNCOMMON CARDS (SPECIAL/PASSIVE/NORMAL) =====
    {
      id: 'card_special_001',
      name: 'Flame Mage',
      description: 'Commands the power of fire',
      hp: 35,
      shield: 8,
      rarity: 'uncommon',
      is_boss: false,
      image_url: null,
    },
    {
      id: 'card_special_002',
      name: 'Frost Wizard',
      description: 'Wields ice and cold',
      hp: 32,
      shield: 10,
      rarity: 'uncommon',
      is_boss: false,
      image_url: null,
    },
    {
      id: 'card_passive_001',
      name: 'Blessed Cleric',
      description: 'Provides healing and support',
      hp: 28,
      shield: 12,
      rarity: 'uncommon',
      is_boss: false,
      image_url: null,
    },
    {
      id: 'card_passive_002',
      name: 'Strategist',
      description: 'Grants tactical advantages',
      hp: 30,
      shield: 10,
      rarity: 'uncommon',
      is_boss: false,
      image_url: null,
    },

    // ===== RARE CARDS (HP) =====
    {
      id: 'card_hp_009',
      name: 'Elite Champion',
      description: 'A hero of many battles',
      hp: 70,
      shield: 15,
      rarity: 'rare',
      is_boss: false,
      image_url: null,
    },
    {
      id: 'card_hp_010',
      name: 'Paladin',
      description: 'Holy warrior with divine protection',
      hp: 65,
      shield: 18,
      rarity: 'rare',
      is_boss: false,
      image_url: null,
    },

    // ===== RARE CARDS (SHIELD) =====
    {
      id: 'card_shield_006',
      name: 'Fortress',
      description: 'An immovable barrier',
      hp: 40,
      shield: 40,
      rarity: 'rare',
      is_boss: false,
      image_url: null,
    },

    // ===== RARE CARDS (SPECIAL/PASSIVE/NORMAL) =====
    {
      id: 'card_special_003',
      name: 'Archmage',
      description: 'Master of arcane arts',
      hp: 45,
      shield: 12,
      rarity: 'rare',
      is_boss: false,
      image_url: null,
    },
    {
      id: 'card_special_004',
      name: 'Shadow Assassin',
      description: 'Strikes from the darkness',
      hp: 40,
      shield: 8,
      rarity: 'rare',
      is_boss: false,
      image_url: null,
    },
    {
      id: 'card_passive_003',
      name: 'Ancient Sage',
      description: 'Wisdom grants resilience',
      hp: 50,
      shield: 15,
      rarity: 'rare',
      is_boss: false,
      image_url: null,
    },
    {
      id: 'card_normal_004',
      name: 'Blade Master',
      description: 'Unmatched swordsmanship',
      hp: 48,
      shield: 10,
      rarity: 'rare',
      is_boss: false,
      image_url: null,
    },

    // ===== EPIC CARDS =====
    {
      id: 'card_epic_001',
      name: 'Dragon Knight',
      description: 'Bonded with a dragon spirit',
      hp: 85,
      shield: 20,
      rarity: 'epic',
      is_boss: false,
      image_url: null,
    },
    {
      id: 'card_epic_002',
      name: 'Phoenix Guardian',
      description: 'Rises from defeat stronger',
      hp: 75,
      shield: 25,
      rarity: 'epic',
      is_boss: false,
      image_url: null,
    },
    {
      id: 'card_epic_003',
      name: 'Void Warden',
      description: 'Commands the power of the void',
      hp: 70,
      shield: 22,
      rarity: 'epic',
      is_boss: false,
      image_url: null,
    },

    // ===== LEGENDARY CARDS =====
    {
      id: 'card_legendary_001',
      name: 'Eternal Champion',
      description: 'Legendary hero of countless victories',
      hp: 100,
      shield: 30,
      rarity: 'legendary',
      is_boss: false,
      image_url: null,
    },
    {
      id: 'card_legendary_002',
      name: 'Celestial Guardian',
      description: 'Blessed by the heavens themselves',
      hp: 95,
      shield: 35,
      rarity: 'legendary',
      is_boss: false,
      image_url: null,
    },

    // ===== BOSS CARDS =====
    {
      id: 'card_boss_001',
      name: 'Tavern Tyrant',
      description: 'The cruel master of the tavern',
      hp: 150,
      shield: 40,
      rarity: 'legendary',
      is_boss: true,
      image_url: null,
    },
    {
      id: 'card_boss_002',
      name: 'Shadow Lord',
      description: 'Ruler of darkness and despair',
      hp: 180,
      shield: 50,
      rarity: 'legendary',
      is_boss: true,
      image_url: null,
    },
    {
      id: 'card_boss_003',
      name: 'Dragon Overlord',
      description: 'Ancient dragon of immense power',
      hp: 200,
      shield: 60,
      rarity: 'legendary',
      is_boss: true,
      image_url: null,
    },

    // ===== ADDITIONAL COMMON CARDS FOR VARIETY =====
    {
      id: 'card_hp_011',
      name: 'Farm Hand',
      description: 'Surprisingly tough from hard labor',
      hp: 33,
      shield: 7,
      rarity: 'common',
      is_boss: false,
      image_url: null,
    },
    {
      id: 'card_hp_012',
      name: 'Tavern Brawler',
      description: 'Seasoned in bar fights',
      hp: 31,
      shield: 9,
      rarity: 'common',
      is_boss: false,
      image_url: null,
    },
    {
      id: 'card_normal_005',
      name: 'Axe Warrior',
      description: 'Cleaves through enemies',
      hp: 29,
      shield: 8,
      rarity: 'common',
      is_boss: false,
      image_url: null,
    },
    {
      id: 'card_normal_006',
      name: 'Ranger',
      description: 'Expert tracker and hunter',
      hp: 27,
      shield: 7,
      rarity: 'common',
      is_boss: false,
      image_url: null,
    },
    {
      id: 'card_shield_007',
      name: 'Sentinel',
      description: 'Always on watch',
      hp: 24,
      shield: 16,
      rarity: 'common',
      is_boss: false,
      image_url: null,
    },
  ]);
};
